### ISSUE TITLE
is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？

### ISSUE THREAD

**Issue by Kumikoo** [Sreyan88/BioAug#1]
is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？

**Comment by Eyeistar** [comment]
你好，我在运行train_dynamic.py时没有运行起来，请问你是按照教程运行的嘛？

**Comment by Kumikoo** [comment]
> 

是的

**Comment by Eyeistar** [comment]
> 
方便加您个联系方式请教您一下可以吗？我这还是没有跑起来

**Comment by Sreyan88** [comment]
您好，您能详细解释一下您的问题吗？谢谢

**Comment by Kumikoo** [comment]
> 您好，您能详细解释一下您的问题吗？谢谢

好的。我从您提供的checkpoint链接中下载了umls-large.pth.tar，然后我设置args.checkpoint路径，当我在运行flair_eval_equal.py文件时，会在tagger = SequenceTagger.load_state_dict(torch.load(checkpoint))这句话中有如下几种报错：
1.当args.checkpoint = "./model/umls-large.pth.tar"时，报错TypeError: load_state_dict() missing 1 required positional argument: 'state_dict'
2.当解压tar文件，args.checkpoint = "./model/checkpoint/data.pkl"，报错_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.
我不太清楚该如何加载这个checkpoint

**Comment by Eyeistar** [comment]
你好，我也是复现论文的呢，目前还没有到flair_eval那一步，目前是pretrain_dynamic跑不通，所以想问问您是怎么跑通的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月1日(周二) 上午8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sreyan88/BioAug] is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？ (Issue #1)




  
您好，您能详细解释一下您的问题吗？谢谢
  
好的。我从您提供的checkpoint链接中下载了umls-large.pth.tar，然后我设置args.checkpoint路径，当我在运行flair_eval_equal.py文件时，会在tagger = SequenceTagger.load_state_dict(torch.load(checkpoint))这句话中有如下几种报错：
 1.当args.checkpoint = "./model/umls-large.pth.tar"时，报错TypeError: load_state_dict() missing 1 required positional argument: 'state_dict'
 2.当解压tar文件，args.checkpoint = "./model/checkpoint/data.pkl"，报错_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified.
 我不太清楚该如何加载这个checkpoint

**Comment by Kumikoo** [comment]
> 你好，我也是复现论文的呢，目前还没有到flair_eval那一步，目前是pretrain_dynamic跑不通，所以想问问您是怎么跑通的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月1日(周二) 上午8:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Sreyan88/BioAug] is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？ (Issue #1) 您好，您能详细解释一下您的问题吗？谢谢 好的。我从您提供的checkpoint链接中下载了umls-large.pth.tar，然后我设置args.checkpoint路径，当我在运行flair_eval_equal.py文件时，会在tagger = SequenceTagger.load_state_dict(torch.load(checkpoint))这句话中有如下几种报错： 1.当args.checkpoint = "./model/umls-large.pth.tar"时，报错TypeError: load_state_dict() missing 1 required positional argument: 'state_dict' 2.当解压tar文件，args.checkpoint = "./model/checkpoint/data.pkl"，报错_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified. 我不太清楚该如何加载这个checkpoint — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

是不是显存不够？我没有改动，就可以跑通

**Comment by Eyeistar** [comment]
> 
运行sh train_dynamic.sh 500 ebmnlp 8 42 5报错如下：
：nott foundic.sh: 2: 
: not foundic.sh: 3: 
train_dynamic.sh: 4: set: Illegal option -
没有改动作者的原代码。

**Comment by Eyeistar** [comment]
> 运行sh train_dynamic.sh 500 ebmnlp 8 42 5报错如下：
> ：nott foundic.sh: 2:
> : not foundic.sh: 3:
> train_dynamic.sh: 4: set: Illegal option -
> 没有改动作者的原代码

运行sh train_dynamic.sh 500 ebmnlp 8 42 5报错如下：
：nott foundic.sh: 2:
: not foundic.sh: 3:
train_dynamic.sh: 4: set: Illegal option -
没有改动作者的原代码

**Comment by Eyeistar** [comment]
> > 你好，我也是复现论文的呢，目前还没有到flair_eval那一步，目前是pretrain_dynamic跑不通，所以想问问您是怎么跑通的？
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年8月1日(周二) 上午8:58 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [Sreyan88/BioAug] is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？ (Issue #1) 您好，您能详细解释一下您的问题吗？谢谢 好的。我从您提供的checkpoint链接中下载了umls-large.pth.tar，然后我设置args.checkpoint路径，当我在运行flair_eval_equal.py文件时，会在tagger = SequenceTagger.load_state_dict(torch.load(checkpoint))这句话中有如下几种报错： 1.当args.checkpoint = "./model/umls-large.pth.tar"时，报错TypeError: load_state_dict() missing 1 required positional argument: 'state_dict' 2.当解压tar文件，args.checkpoint = "./model/checkpoint/data.pkl"，报错_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified. 我不太清楚该如何加载这个checkpoint — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 是不是显存不够？我没有改动，就可以跑通

sh train_dynamic.sh 500 ebmnlp 8 42 5运行后报错如下：
: not foundic.sh: 2: 
: not foundic.sh: 3: 
train_dynamic.sh: 4: set: Illegal option 
目前没有改动原代码

**Comment by Utkarsh4430** [comment]
Hi guys,
Sorry if I misinterpret any messages since I don't speak chinese.
From what I can see, there are 2 separate issues being discussed here
I have updated the code to address the two problems. Can you please try pulling the latest code from the main branch and see if it fixes your issues?

@Kumikoo the UMLS checkpoint and the checkpoint needed for flair_eval_equal was different. flair_eval_equal.py uses a checkpoint trained on the gold only dataset to filter out the augmentations. We call this the consistency step. Please refer to the paper for more details. I have updated the code so you should not face more issues.

@Eyeistar please let me know if you face the issues again.

**Comment by Eyeistar** [comment]
> Sorry if I misinterpret any messages since I don't speak chinese.
> From what I can see, there are 2 separate issues being discussed here
> I have updated the code to address the two problems. Can you please try pulling the latest code from the main branch and see if it fixes your issues?

Hello, I tried using your updated code today. The first thing I want to do is to enhance the data. Did I follow the steps in readme.md? If so, in step 5 of readme.md, execute bash train_ Dynamic.sh 100 bc2gm 8 42 5,

Error train_ Dynamic.sh:

Line 2: $' r': Command not found: Invalid option mic. sh:

Line 3: set: - set: Usage: set [-- abefhkmnptuvxBCHP] [- o option name] [--] [Parameters...]: Invalid option mic. sh:

Line 4: set: - set: Usage: set [-- abefhkmnptuvxBCHP] [- o option name] [--] [Parameters...]

Train_ Dynamic.sh: Line 5: $' r': Command not found.

I still haven't made it through. Could you please provide a detailed explanation of the steps in the data enhancement section.

**Comment by Utkarsh4430** [comment]
Hey! just verifying; there is a space in the shell script file name in the command you used. Also, the letter D is capital.
It should be "train_dynamic.sh" instead of "train_ Dynamic.sh".

**Comment by Kumikoo** [comment]
> Hey! just verifying; there is a space in the shell script file name in the command you used. Also, the letter D is capital. It should be "train_dynamic.sh" instead of "train_ Dynamic.sh".

Thanks for your help. And I have another question. I can't find the "umls-rel2id.json" file so that I can't run `get_model()` in pretrain.py.

**Comment by Utkarsh4430** [comment]
@Kumikoo I have uploaded the file and also updated the readme. Please let me know if you have any more doubts!

Just adding that this is not mandatory to run our code. We have already provided a trained model in the repo. We have also provided the datasets with relations already available. You can start directly from Step 5!
This step is only required if you want to train your own UMLS-based relation extraction model using OpenNRE.

**Comment by MingsenBoy** [comment]
When i try to reproduce the results of BioAug and following the instructions in the README.md (sh train_dynamic.sh 100(200) bc2gm(bc5dr、ncbi) 8 42 5), I encountered an error in the flair_eval_equal.py stage: FileNotFoundError: [Errno 2] No such file or directory: '../datasets-precompute/bc2gm/100/train_processed-5-100-42--tokenfix.txt'.

I discovered that commenting out lines 220-243 in the test-dynamic.py resolves the error. 
However, the final results can not achieve the similar performance reported in the paper. 
My Python version is 3.8, and all packages are the same as specified in requirement.txt. Are there specific package versions for the dataset, nltk, and Flair? Or have I made an error in any step? 

appreciate any help, sincerely.

**Comment by Sreyan88** [comment]
Hi @MingsenBoy , what do your scores look like, and for which dataset? This information will help us help you. Thank You!

**Comment by MingsenBoy** [comment]
I have run 100 bc2gm 8 42 5 f1 score 0.4298, 200 bc2gm 16 42 5 f1 score 0.5499, 100 bc5dr 16 42 5 f1 score 0.7011, 200 bc5dr 16 42 5 f1 score 0.7757, 100 ncbi 8 42 5 f1 score 0.56, 200 ncbi 8 42 5 f1 score 0.6713, 500 ncbi 8 42 5 f1 score 0.7525.
Are there specific package versions for the dataset, nltk, and Flair?

looking forward your feedback, sincerely.

**Comment by MingsenBoy** [comment]
> Hi @MingsenBoy , what do your scores look like, and for which dataset? This information will help us help you. Thank You!

@Sreyan88 @Utkarsh4430 
I have run 100 bc2gm 8 42 5 f1 score 0.4298, 200 bc2gm 16 42 5 f1 score 0.5499, 100 bc5dr 16 42 5 f1 score 0.7011, 200 bc5dr 16 42 5 f1 score 0.7757, 100 ncbi 8 42 5 f1 score 0.56, 200 ncbi 8 42 5 f1 score 0.6713, 500 ncbi 8 42 5 f1 score 0.7525.
Are there specific package versions for the dataset, nltk, and Flair?

looking forward your feedback, sincerely.

**Comment by xiaohutong** [comment]
您好 如何把原始数据集转换成带有关键词的数据集呢

**Comment by xiaohutong** [comment]
> 你好，我也是复现论文的呢，目前还没有到flair_eval那一步，目前是pretrain_dynamic跑不通，所以想问问您是怎么跑通的？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月1日(周二) 上午8:58 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Sreyan88/BioAug] is:issue is:open 当我执行flair_eval_equal.py，载入checkpoint的时候报错，请问checkpoint是否是提供下载压缩包中的data.pkl？ (Issue #1) 您好，您能详细解释一下您的问题吗？谢谢 好的。我从您提供的checkpoint链接中下载了umls-large.pth.tar，然后我设置args.checkpoint路径，当我在运行flair_eval_equal.py文件时，会在tagger = SequenceTagger.load_state_dict(torch.load(checkpoint))这句话中有如下几种报错： 1.当args.checkpoint = "./model/umls-large.pth.tar"时，报错TypeError: load_state_dict() missing 1 required positional argument: 'state_dict' 2.当解压tar文件，args.checkpoint = "./model/checkpoint/data.pkl"，报错_pickle.UnpicklingError: A load persistent id instruction was encountered, but no persistent_load function was specified. 我不太清楚该如何加载这个checkpoint — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好 如何把原始数据集转换成带有关键词的数据集呢

**Comment by Sreyan88** [comment]
Closing this as the problem was solved over email. Please use --use_consistency = True for all experiments to replicate paper scores.
